name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '10 1-9 * * 1-5'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: execute
      env: 
        WEIXIN_TOKEN: ${{ secrets.WEIXIN_TOKEN }}
      run: bash b.sh
