name: Go

on:
  schedule:
    - cron: '10 1,7 * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: execute
      env: 
        WEIXIN_TOKEN: ${{secrets.WEIXIN_TOKEN}}
      run: curl --request POST --url 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=707f5782-9933-4da8-b883-07fe693ceb21' --header 'Content-Type: application/json' --data '{"msgtype":"text","text":{"content":"生活小蜜提醒您现在是 $data ,您该喝水了，休息一下"}}'
